on: 
  push:
    branches:
      - release

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install unpub_auth
        run: dart pub global activate unpub_auth
        
      - name: Create credentials file
        run: echo $PUB_CREDENTIALS > ~/pub-credentials.json
        env:
          PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
          
      - name: Migrate credentials
        run: unpub_auth migrate ~/pub-credentials.json
        
      - name: Send credentials to the Dart client
        run: unpub_auth get | dart pub token add https://pub.dev

      - name: Publish
        run: dart pub publish
