on: 
  push:
    branches:
      [release, master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          credential: ${{ secrets.PUB_CREDENTIALS }}
          flutter_package: false
          skip_test: true
          dry_run: false
